### ISSUE TITLE
Tourelles qui se tire dessus

### ISSUE THREAD

**Issue by DocThomus** [ProjectWarbot/Warbot#31]
Explication : Lorsqu'une tourelle tire, le projectile est créé sur elle. Du coup, il rentre en collision au tick suivant, et explose. 
Reproduction du bug : Avec la team de base en Java, faire tirer une tourelle sur un rocketLauncher ennemi.

**Comment by TsubameDono** [comment]
Les tourelles ne tiraient pas des WarRocket mais des agents WarDeathRocket qui n'ont aucune autonomie par défaut dans le fichier de configuration. De ce fait, ce n'était pas un problème de collision mais de durée de vie.

Maintenant les tourelles WarTurret lancent des agents WarRocket.

Problème réglé.
